g_caption = "Sidescroller"
g_max_fps = 60  # Maximum FPS and game speed

g_height_width = 1  # Width of each rectangle that makes up the terrain. (display_width % height_width) should be 0.
g_terrain_height = 3  # How high up the terrain is on the screen
g_noise_multiplier = 100  # How much to multiply the values generated by the noise algorithm by
g_map_length = 3  # How "zoomed in" the map is. Higher values mean less zoom       Set to high value for wacky meme
g_octaves = 5  # More octaves adds more variation to the terrain
g_y = 1  # Fix the y value because only 1D noise is needed from the 2D noise algorithm
g_seed = 0  # Seed for the noise generator. Different seeds will give different terrain

# Colour RGB values
g_black = (0, 0, 0)
g_white = (255, 255, 255)
g_red = (255, 0, 0)
g_green = (0, 255, 0)
g_blue = (0, 0, 255)
g_dark_green = (0, 200, 0)
g_orange = (255, 165, 0)
g_brown = (87, 68, 15)
g_grass = (30, 133, 58)
g_sky = (13, 190, 217)
g_dark_blue = (0, 12, 87)
g_dark_brown = (56, 12, 12)
g_gold = (255, 215, 0)

g_gravity = 0.5

# Player properties
g_player_width = 25
g_player_height = 50
g_player_speed = 4  # Needs to be integer
g_player_melee_speed = 5
g_player_jump_speed = 15
g_player_health = 20
g_player_melee_damage = 4
g_player_melee_x_range = 50
g_player_melee_y_range = 50
g_player_backwards_melee_range = 20
g_player_melee_cooldown = 15

g_player_bullet_damage = 1
g_player_inaccuracy = 0.02
g_player_shoot_cooldown = 10

g_player_health_bar_width = 300
g_player_health_bar_height = 30
g_player_health_bar_x = 50

# Enemy properties
g_max_enemies = 5
g_enemy_spawn_chance = 50
g_enemy_melee_chance = 0.6
g_enemy_max_spawn_cooldown = 500
g_enemy_min_spawn_cooldown = 60
g_enemy_min_cooldown_time = 1000
g_enemy_speed = g_player_speed - 1
g_enemy_player_detection_range = 800
g_enemy_health = 10
g_enemy_melee_damage = 1
g_enemy_melee_x_range = 30
g_enemy_melee_y_range = 30
g_enemy_melee_cooldown = 30

g_enemy_bullet_damage = 1
g_enemy_inaccuracy = 0.1
g_enemy_shoot_cooldown = 50
g_enemy_shoot_range = 400
g_enemy_back_off_range = 250

g_enemy_health_bar_width = 40
g_enemy_health_bar_height = 10
g_height_above_enemy = 25

g_bullet_side_length = 5
g_bullet_colour = g_black
g_bullet_speed = 10

g_coin_side_length = 15
g_coin_ground_distance = 200

g_health_pack_side_lentgh = 30
g_health_pack_ground_distance = 100

# Platform properties
g_platform_width = 200
g_platform_height = 10
g_platform_colour = g_brown
g_platform_ground_distance = 150
g_max_platforms = 3

g_button_width = 100
g_button_height = 50
g_wide_button_width = 200
